name: "Run tests"
on: [pull_request, push]

jobs:
  check_pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: "Setup pnpm"
        uses: pnpm/action-setup@v4

      - name: "Setup Node.js"
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: "Setup bun"
        uses: oven-sh/setup-bun@v2

      - name: "Install dependencies"
        run: pnpm install --frozen-lockfile

      - name: "Type check"
        run: bun run typecheck

      - name: "Build release"
        run: bun run build-release

      - name: "Run tests"
        run: bun test

      - name: "check for uncommitted changes"
        # Ensure no changes, but ignore node_modules dir since dev/fresh ci deps installed.
        run: |
          git diff --exit-code --stat -- . ':!node_modules' ':!pnpm-lock.yaml' \
          || (echo "##[error] found changed files after build. please 'pnpm run build && pnpm run format'" \
                   "and check in all changes" \
              && exit 1)
